// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tlrnxdmuxsvhegburrql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscm54ZG11eHN2aGVnYnVycnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzI1ODYsImV4cCI6MjA2Njg0ODU4Nn0.Q0xwUiXNbkixxOFzDzoavPs_UL9r6vajDsDeThWw3Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);